(folderURL as text, optional includeSubFolders as nullable logical) as table =>   
let
    Folder = Text.Replace(folderURL,"%20"," "),
    SplitSite = "sites/",
    SplitSiteLen = Text.Length(SplitSite),
    SplitSitePos = Text.PositionOf(Folder,SplitSite,Occurrence.First,Comparer.OrdinalIgnoreCase),
    Folder2 = Text.Range(Folder,SplitSitePos+SplitSiteLen),
    Position2 =  Text.PositionOf(Folder2,"/",Occurrence.First),
    SharePointURL = Text.Start(Folder,SplitSitePos+SplitSiteLen+Position2+1),
    Source = SharePoint.Files(SharePointURL, [ApiVersion = 15]),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = Folder)),
    RemoveFolderPath = Table.RemoveColumns(#"Filtered Rows",{"Folder Path"}),
    MakeNameKey = Table.AddKey(RemoveFolderPath,{"Name"},true)
in
    if includeSubFolders = true then #"Filtered Rows" else MakeNameKey
